### ISSUE TITLE
Errors  facebook2telegram.py

### ISSUE THREAD

**Issue by d9994** [s1cp/FacebookPages2Telegram#8]
Hello.
Errors when i run python facebook2telegram.py :
Traceback (most recent call last):
  File "facebook2telegram.py", line 671, in <module>
    main()
  File "facebook2telegram.py", line 653, in main
    loadSettingsFile(settings_path)
  File "facebook2telegram.py", line 61, in loadSettingsFile
    config.read(filename)
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/karadm/telegram/facebook/fbpages-telegram-bot-master/botsettings.ini', line: 2
'locale: en_US\n'

**Comment by freeroid** [comment]
Did you found any solution? i am getting similar errors.

**Comment by freeroid** [comment]
[root@centos-2gb-nbg1-1 fbpages-telegram-bot]# python3.6 facebook2telegram.py
Loaded settings:
Locale: en-US
Admin ID: XXXXXXx
Channel: XXXXXXX
Refresh rate: 300.0
Allow Status: False
Allow Photo: True
Allow Video: True
Allow Link: True
Allow Shared: True
Allow Message: True
Getting most recent posts dates...
Traceback (most recent call last):
  File "facebook2telegram.py", line 671, in <module>
    main()
  File "facebook2telegram.py", line 658, in main
    getMostRecentPostsDates(facebook_pages, dates_path)
  File "facebook2telegram.py", line 216, in getMostRecentPostsDates
    fields='name,posts.limit(1){created_time}')
  File "/usr/lib/python3.6/site-packages/facebook/__init__.py", line 134, in get_objects
    args["ids"] = ",".join(ids)
TypeError: can only join an iterable
