### ISSUE TITLE
Facebook GraphAPIError #200

### ISSUE THREAD

**Issue by audax67** [s1cp/FacebookPages2Telegram#9]
I have a problem getting the Botscript working

> 

> jk@ubuntu:~/fbpages-telegram-bot$ python3 facebook2telegram.py
> Loaded settings:
> Locale: de-DE
> Admin ID: 12345678
> Channel: @my_Telegram_Channel
> Refresh rate: 300.0
> Allow Status: False
> Allow Photo: True
> Allow Video: True
> Allow Link: True
> Allow Shared: True
> Allow Message: True
> Getting most recent posts dates...
> Traceback (most recent call last):
>   File "facebook2telegram.py", line 671, in <module>
>     main()
>   File "facebook2telegram.py", line 658, in main
>     getMostRecentPostsDates(facebook_pages, dates_path)
>   File "facebook2telegram.py", line 216, in getMostRecentPostsDates
>     fields='name,posts.limit(1){created_time}')
>   File "/home/jk/.local/lib/python3.5/site-packages/facebook/__init__.py", line 114, in get_objects
>     return self.request(self.version + "/", args)
>   File "/home/jk/.local/lib/python3.5/site-packages/facebook/__init__.py", line 272, in request
>     raise GraphAPIError(result)
> facebook.GraphAPIError: (#200) Access to this data is temporarily disabled for non-active accounts due to changes we are making to the Facebook Platform

Is it right, that facebook changed something with the API or do I have another problem?

**Comment by 00aixxia00** [comment]
Did you find an answer ? Having the same problem :(
